apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface-chatbot-deployment
  labels:
    app: interface-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interface-chatbot
  template:
    metadata:
      labels:
        app: interface-chatbot
    spec:
      containers:
        - name: interface-chatbot-container
          image: interface-chatbot:latest
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-key
                  key: OPENAI_API_KEY
            - name: SERPAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: serpapi-key
                  key: SERPAPI_KEY
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: sender-email
                  key: SENDER_EMAIL
            - name: SENDER_PIN
              valueFrom:
                secretKeyRef:
                  name: sender-pin
                  key: SENDER_PIN
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: interface-chatbot-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30808
  selector:
    app: interface-chatbot
